require 'bundler/setup'

lib = File.expand_path('../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require './config'
require 'static-sprockets/tasks/assets'
require 'static-sprockets/tasks/layout'
require 'dashboard/installer_import'
require 'fileutils'

namespace :assets do
  task :clean do
    system("touch ./lib/javascripts/dashboard/static-config.js.erb")
    if ENV['ASSET_CACHE_DIR'].nil?
      system("rm -rf "+ StaticSprockets.config[:output_dir])
    end
  end
end

task :compile => ["assets:clean", "assets:precompile", "layout:compile"] do
end
